### ISSUE TITLE
[FR] Make FairEmail go directly to the mail when the particular notification is tapped

### ISSUE THREAD

**Issue by TheMadRuffian** [M66B/open-source-email#141]
I feel that when the sender and the subject are visible in the notification, the rational response of the app is to take me directly to that particular mail instead of the unified inbox.

**Comment by M66B** [comment]
There is one thing that makes this complicated: threads.

**Comment by TheMadRuffian** [comment]
If the rest of the messages in a thread are made to be fetched from the server when required through searching, would it make FairEmail deal with the just current message?

**Comment by M66B** [comment]
The complication is not about fetching messages, but about what to show. IMO the thread should be shown if there is any to keep things consistent and to have an overview of the messages, especially when more new messages in the same thread arrived.

**Comment by TheMadRuffian** [comment]
Sounds good. Maybe a 'scroll up' gesture would bring back the previous messages in the same thread?

**Comment by M66B** [comment]
Swipe gestures in the message view do not work properly because all texts are selectable.

**Comment by TheMadRuffian** [comment]
How about a 'Load more' option at the top (even bottom would do) of the received message to bring back the thread?

**Comment by M66B** [comment]
It is not about loading more messages, it is about missing new messages. Image several people participating in a discussion. In this case you want to read the oldest new message first.

Anyway, if added, it will be consistent with like how tapping on an entry in the unified inbox works, which makes is more complicated because the new message notification is about a single message.

**Comment by M66B** [comment]
There could be more messages than can be shown by notifications. Also, this doesn't give an overview like the thread view does.

**Comment by TheMadRuffian** [comment]
Grouping the notifications might help but IMO feels counterintuitive. How about leaving the behavior of thread as it is and implement it for the rest? But then again doesn't feel consistent enough.

**Comment by M66B** [comment]
The notifications are fine, it is about what to do when tapping on the notification. Anyway, it will be the thread view if there is a thread or the unified inbox view. Anything else would inconsistent.

Showing the unified inbox view like it is now has as advantage it gives you an overview of all messages.

Notifications of individual messages was added to be able to mark individual messages as read and to be able to trash them, not to navigate to individual messages.

**Comment by heinhuiz** [comment]
If you would go for the option to open the message when there is no thread, otherwise open the thread, then only the notification of that single message or all the messages in the thread should be cleared. Only going back to the unified inbox should clear all notifications at once, otherwise the notifications have to be dealt with one by one (thread by thread).
To keep things simple then, there should still be a way to open the unified inbox instead with one tap, which would probably require an additional first notification at the top.
I don't think that's a preferable situation.

**Comment by M66B** [comment]
Because of the complications, this will not be implemented.
