### ISSUE TITLE
Setting for selecting default inbox

### ISSUE THREAD

**Issue by Sonic112** [M66B/open-source-email#47]
Make a setting for selecting which default inbox to show (instead of just having unified as default like it is now)

**Comment by M66B** [comment]
The unified inbox is what most people want to see and I am trying to keep the number of settings as low as possible because each new settings complicates usage (maybe not for you, but it does for less experienced people). I am also assuming that people want to read the email received, else there is no point in configuring an account.

You can always navigate to the specific inbox you want to see.

Nevertheless, I like to know/understand why you want this.

**Comment by Sonic112** [comment]
OK, to me unified inboxes when having 5 accounts just look like a mess, perhaps I'll get used to it.
My proposal might be a future option if more people is asking for it :)

**Comment by Primokorn** [comment]
Additional request;
*Disable notifications for the excluded account*

**Comment by M66B** [comment]
@Primokorn new email notifications will only be shown for unified inbox folders.
