### ISSUE TITLE
Delete sent messages from outbox

### ISSUE THREAD

**Issue by Sonic112** [M66B/open-source-email#51]
Send emails is shown in Outbox not in Sent. Otherwise the app works fine sending and receiving.

**Comment by M66B** [comment]
This is a problem of your provider. You can enable the account option *Store sent messages* to workaround this.

**Comment by Sonic112** [comment]
One more question. How do I delete the old messages in the Outbox then?

**Comment by M66B** [comment]
For now you will need to reinstall.

**Comment by M66B** [comment]
Messages with errors in the outbox can already be deleted.
Messages without errors cannot be deleted and this will not be made possible.

**Comment by rancidfrog** [comment]
With outlook sent message gets saved in draft and stays in outlook and stored in sent folder:
![](https://i.imgur.com/eLikpBX.png) 
All 1 messages in the 3 different folders are the same message that I sent to test.

Store sent messages is currently disabled:
![](https://i.imgur.com/IpIWaz3.png)

But I am pretty sure enabling it will only cause duplicate sent meassages, as that is what happens with k9-mail

**Comment by M66B** [comment]
Draft messages are deleted before placing a message in the sent folder, so I don't see how they can stay behind.

Moving messages from the outbox to sent reply on feedback of the provider. Deleting messages from the outbox is not an option because that could result in permanent losing the message. Moving the message to the sent folder might result in duplicates. So, there are few options here.

I cannot reproduce this problem, so unless you describe the exact steps to reproduce this, there is little I can do.

**Comment by M66B** [comment]
It appears that I can reproduce this issue with Outlook. The cause is that Outlook overrides the set message ID. The only way to fix this is to delete messages from the outbox after sending, for which I will add an option, provided you create a new issue for this to remind me of this. It doesn't fit in this issue anymore.

**Comment by rancidfrog** [comment]
Done.
