### ISSUE TITLE
OPENSSL_internal: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by gilcu3** [M66B/open-source-email#56]
I'm getting an ssl error while setting up account, and as such I cannot get to the step where the about button is visible, so getting exact error log is hard...

I'm trying to connect to a STARTTLS imap server, and I'm getting (in a toast message):
OPENSSL_internal: WRONG_VERSION_NUMBER in boringssl library

**Comment by M66B** [comment]
This mean your provider is using an outdated, insecure SSL version. Which email provider are you using?

**Comment by gilcu3** [comment]
Well, it's only accessible in our internal network, and I won't be able to make them update it, any way to overcome it (granting it'll be insecure and the user should be aware of it)?

**Comment by M66B** [comment]
After some research: this message is likely being caused by not using SSL at all, so make sure you are using the right port number.

Connections without SSL are insecure and will not be supported. It is 2018.

**Comment by gilcu3** [comment]
The most likely reason is self signed certificate, as my config in Aqua Mail is StartTLS (accept any) port 143. And if I put strict check, it displays error. So, self signed certificates will be supported? Thanks for your time researching though

**Comment by M66B** [comment]
Self signed certificates are not supported for security reasons. It is easy to request certificates from Letsencrypt for free these days, so there is really no reason to use self signed certificates besides maybe testing. And certainly not in a corporate environment.

I don't want to support insecure stuff and the goal is to assure security, so this will not be added as 'feature'.

**Comment by gilcu3** [comment]
Ahh, yes my server is IMAP with STARTTLS, I'll have to study the difference carefully, cos as far I could see it was secure enough, do you have any pointer to your security reasons?

**Comment by M66B** [comment]
See here:
https://www.eff.org/nl/deeplinks/2018/06/announcing-starttls-everywhere-securing-hop-hop-email-delivery

"Additionally, even if you configure STARTTLS perfectly and use a valid certificate, there’s still no guarantee your communication will be encrypted."

The fact that a STARTTLS connection starts not encrypted should say enough.

I have yet to see a mayor email provider which doesn't support real SSL, so I see no reason to support less secure connections.

Note that STARTTLS for SMTP is supported because there are too many providers no supporting SMTP over real SSL.
