### ISSUE TITLE
[FR] Show avatars

### ISSUE THREAD

**Issue by Primokorn** [M66B/open-source-email#61]
The default view could be considered as a **Compact** view.
Please add an option to have a **Standard** view and/or a **Large** view to add more information such as:
• name of the account related to the email
• the first 100 caracters of the body of the text (more or less)
• avatars
• medias displayed as thumbnails
• ...

Something similar to Inoreader (RSS feader).

**Comment by M66B** [comment]
The account name is shown in the unified inbox since a few versions.

Showing the first characters of a message text would slow down things because messages texts are not stored in the database (message texts are sometimes too large for this) and besides that the subject should tell you what the message is about.

Although most people don't have avatars, I will see if I can add this in a later version.

I am not sure what you mean by 'medias'.

In any case there will be no option for a compact/standard/large view because the goal is to have no options.

**Comment by Primokorn** [comment]
Forget "medias" since you decline the other requests. It requires even more space.
However I have no performance issue with my current email app and showing the first characters.
I sometimes send emails without subject too.

Avatars can be used for multi-selection btw.

IMHO it's a delicate decision to give no options to your users.

**Comment by M66B** [comment]
Fetching contacts photos can be done like this:
https://stackoverflow.com/a/14103294/1794097

Each email requires two contacts providers queries to get the photo URI, which has to be transformed to a drawable. This needs to be done asynchronous. Nevertheless, I am afraid there will be a significant performance impact.

**Comment by M66B** [comment]
As predicted, scrolling messages stutters on lower end devices.
I have added an option to show avatars (default disabled).

**Comment by M66B** [comment]
I was able to fix the stutting :-)
