### ISSUE TITLE
mark read when swiping to trash

### ISSUE THREAD

**Issue by chantoine** [M66B/open-source-email#83]
When swiping to move a mail to trash folder, it should also be marked as read.

**Comment by M66B** [comment]
I don't think everybody would agree on this. In any case I do not. The next version has long press to mark as read.

**Comment by Primokorn** [comment]
Good idea IMHO since I don't see the use case of keeping unread emails in the Trash folder.

**Comment by M66B** [comment]
Unread is unread. And this is a piece of information. Choosing to automatically mark as read will result in somebody complaining.

Example use case: you accidentally deleted a message, which is easily located in a long list because it is still unread.

Note that marking read will be easy in the next release.
